In [56]:
import pandas as pd

In [57]:
import pandas as pd

df = pd.read_csv(r"D:\archive\Ubar Row.csv")
print(df.head())

         Date      Time    Booking ID   Booking Status   Customer ID  \
0  2024-03-23  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"
1  2024-11-29  18:01:39  "CNR1326809"       Incomplete  "CID4604802"
2  2024-08-23  08:56:10  "CNR8494506"        Completed  "CID9202816"
3  2024-10-21  17:17:25  "CNR8906825"        Completed  "CID2610914"
4  2024-09-16  22:08:00  "CNR1950162"        Completed  "CID9933542"

    Vehicle Type      Pickup Location      Drop Location  Avg VTAT  Avg CTAT  \
0          eBike          Palam Vihar            Jhilmil       NaN       NaN
1       Go Sedan        Shastri Nagar  Gurgaon Sector 56       4.9      14.0
2           Auto              Khandsa      Malviya Nagar      13.4      25.8
3  Premier Sedan  Central Secretariat           Inderlok      13.1      28.5
4           Bike     Ghitorni Village        Khan Market       5.3      19.6

   ...  Reason for cancelling by Customer Cancelled Rides by Driver  \
0  ...                                NaN                       NaN
1  ...                                NaN                       NaN
2  ...                                NaN                       NaN
3  ...                                NaN                       NaN
4  ...                                NaN                       NaN

   Driver Cancellation Reason Incomplete Rides  Incomplete Rides Reason  \
0                         NaN              NaN                      NaN
1                         NaN              1.0        Vehicle Breakdown
2                         NaN              NaN                      NaN
3                         NaN              NaN                      NaN
4                         NaN              NaN                      NaN

  Booking Value  Ride Distance  Driver Ratings  Customer Rating  \
0           NaN            NaN             NaN              NaN
1         237.0           5.73             NaN              NaN
2         627.0          13.58             4.9              4.9
3         416.0          34.02             4.6              5.0
4         737.0          48.21             4.1              4.3

   Payment Method
0             NaN
1             UPI
2      Debit Card
3             UPI
4             UPI

[5 rows x 21 columns]

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [60]:
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,10500.0,27000.0,9000.0,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,1.0,1.0,1.0,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,0.0,0.0,0.0,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,1.0,1.0,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,1.0,1.0,1.0,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,1.0,1.0,1.0,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,1.0,1.0,1.0,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,1.0,1.0,1.0,4277.000000,50.000000,5.000000,5.000000

In [61]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [62]:
df['Reason for cancelling by Customer'] = df['Reason for cancelling by Customer'].fillna('Unknown')
df['Driver Cancellation Reason'] = df['Driver Cancellation Reason'].fillna('Unknown')
df['Incomplete Rides Reason'] = df['Incomplete Rides Reason'].fillna('Unknown')
df['Payment Method'] = df['Payment Method'].fillna('Unknown')

df['Avg VTAT'] = df['Avg VTAT'].fillna(0)
df['Avg CTAT'] = df['Avg CTAT'].fillna(0)
df['Cancelled Rides by Customer'] = df['Cancelled Rides by Customer'].fillna(0)
df['Cancelled Rides by Driver'] = df['Cancelled Rides by Driver'].fillna(0)
df['Incomplete Rides'] = df['Incomplete Rides'].fillna(0)
df['Booking Value'] = df['Booking Value'].fillna(0)
df['Ride Distance'] = df['Ride Distance'].fillna(0)
df['Driver Ratings'] = df['Driver Ratings'].fillna(0)
df['Customer Rating'] = df['Customer Rating'].fillna(0)

In [63]:
df.isnull().sum()

Date                                 0
Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
Avg VTAT                             0
Avg CTAT                             0
Cancelled Rides by Customer          0
Reason for cancelling by Customer    0
Cancelled Rides by Driver            0
Driver Cancellation Reason           0
Incomplete Rides                     0
Incomplete Rides Reason              0
Booking Value                        0
Ride Distance                        0
Driver Ratings                       0
Customer Rating                      0
Payment Method                       0
dtype: int64

In [64]:
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,7.864407,19.821753,0.070000,0.180000,0.060000,345.641220,16.753168,2.623215,2.730842
std,4.230640,15.452834,0.255148,0.384189,0.237488,403.423487,16.291118,2.082283,2.165548
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.800000,22.000000,0.000000,0.000000,0.000000,244.000000,13.060000,3.900000,4.100000
75%,11.000000,32.900000,0.000000,0.000000,0.000000,521.000000,30.650000,4.300000,4.600000
max,20.000000,45.000000,1.000000,1.000000,1.000000,4277.000000,50.000000,5.000000,5.000000

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           150000 non-null  float64
 9   Avg CTAT                           150000 non-null  float64
 10  Cancelled Rides by Customer        150000 non-null  float64
 11  Reason for cancelling by Customer  150000 non-null  object
 12  Cancelled Rides by Driver          150000 non-null  float64
 13  Driver Cancellation Reason         150000 non-null  object
 14  Incomplete Rides                   150000 non-null  float64
 15  Incomplete Rides Reason            150000 non-null  object
 16  Booking Value                      150000 non-null  float64
 17  Ride Distance                      150000 non-null  float64
 18  Driver Ratings                     150000 non-null  float64
 19  Customer Rating                    150000 non-null  float64
 20  Payment Method                     150000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [68]:
df.to_csv("Ubar Row.csv",index=False)